"""
RUParked FastAPI Backend

Serves parking lot occupancy data from the YOLO detector to the React frontend.

Run with: uvicorn backend:app --reload --port 8000
"""

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
import json
from pathlib import Path
from typing import Optional
import os

app = FastAPI(
    title="RUParked API",
    description="Parking lot occupancy detection API for Rutgers University",
    version="1.0.0"
)

# Allow React frontend to access API (development and production origins)
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:3000",      # React default
        "http://localhost:5173",      # Vite default
        "http://localhost:5174",      # Vite alternate
        "http://127.0.0.1:3000",
        "http://127.0.0.1:5173",
    ],
    allow_credentials=True,
    allow_methods=["GET"],
    allow_headers=["*"],
)

# Path to the occupancy data file generated by parking_detector.py
OCCUPANCY_FILE = Path("occupancy_data.json")
SPOT_MAPPING_FILE = Path("spot_mapping.json")
MANUAL_ZONES_FILE = Path("manual_parking_zones.json")


def get_occupancy_data() -> dict:
    """Load the current occupancy data from JSON file."""
    if OCCUPANCY_FILE.exists():
        with open(OCCUPANCY_FILE) as f:
            return json.load(f)
    return None


@app.get("/")
def root():
    """API root - returns basic info."""
    return {
        "name": "RUParked API",
        "version": "1.0.0",
        "endpoints": {
            "/api/lots/yellow-lot/status": "Get full lot status",
            "/api/lots/yellow-lot/spots": "Get spots array only",
            "/api/lots/yellow-lot/summary": "Get occupancy summary",
            "/api/health": "Health check"
        }
    }


@app.get("/api/health")
def health_check():
    """Health check endpoint."""
    data_available = OCCUPANCY_FILE.exists()
    return {
        "status": "healthy",
        "data_available": data_available,
        "occupancy_file": str(OCCUPANCY_FILE),
    }


@app.get("/api/lots/yellow-lot/status")
def get_lot_status():
    """Return current parking lot occupancy status.
    
    This is the main endpoint the React frontend polls every 10-60 seconds.
    Returns complete lot data including all spots with their occupancy status.
    """
    data = get_occupancy_data()
    if data:
        return data
    
    # Return empty structure if no data available yet
    return {
        "error": "No data available - detector may not be running",
        "timestamp": None,
        "lot_name": "Yellow Lot",
        "camera_section": "Yellow-NW",
        "total_spots": 0,
        "available": 0,
        "occupied": 0,
        "occupancy_rate": 0,
        "spots": []
    }


@app.get("/api/lots/yellow-lot/spots")
def get_spots():
    """Return just the spots array.
    
    Useful for lightweight polling when you only need spot status updates.
    """
    data = get_occupancy_data()
    if data:
        return {
            "timestamp": data.get("timestamp"),
            "spots": data.get("spots", [])
        }
    return {"timestamp": None, "spots": []}


@app.get("/api/lots/yellow-lot/summary")
def get_summary():
    """Return occupancy summary without individual spot data.
    
    Lightweight endpoint for dashboard widgets.
    """
    data = get_occupancy_data()
    if data:
        return {
            "timestamp": data.get("timestamp"),
            "lot_name": data.get("lot_name", "Yellow Lot"),
            "total_spots": data.get("total_spots", 0),
            "available": data.get("available", 0),
            "occupied": data.get("occupied", 0),
            "occupancy_rate": data.get("occupancy_rate", 0),
        }
    return {
        "timestamp": None,
        "lot_name": "Yellow Lot",
        "total_spots": 0,
        "available": 0,
        "occupied": 0,
        "occupancy_rate": 0,
    }


@app.get("/api/lots/yellow-lot/mapping")
def get_spot_mapping():
    """Return the spot mapping configuration.
    
    Maps detector spot IDs to frontend display labels.
    """
    if SPOT_MAPPING_FILE.exists():
        with open(SPOT_MAPPING_FILE) as f:
            return json.load(f)
    
    # Return default mapping based on manual zones if mapping file doesn't exist
    if MANUAL_ZONES_FILE.exists():
        with open(MANUAL_ZONES_FILE) as f:
            zones = json.load(f)
            return {
                "lot_name": "Yellow Lot",
                "camera_section": "Yellow-NW",
                "spots": [
                    {
                        "detector_id": zone.get("id", idx),
                        "frontend_id": f"S{idx + 1}",
                        "center": zone.get("center", [0, 0])
                    }
                    for idx, zone in enumerate(zones)
                ]
            }
    
    return {"error": "No mapping configuration available"}


@app.get("/api/lots")
def list_lots():
    """List all available parking lots.
    
    Currently only Yellow Lot is implemented.
    """
    return {
        "lots": [
            {
                "id": "yellow-lot",
                "name": "Yellow Lot",
                "campus": "Livingston",
                "status": "active" if OCCUPANCY_FILE.exists() else "offline"
            }
        ]
    }


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000, reload=True)
